spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jedis
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true